### ISSUE TITLE
crash in example

### ISSUE THREAD

**Issue by faassen** [geertj/gruvi#24]
I tried the fortune web server example from the docs. It starts up:

```
Listen on 127.0.0.1:34810
```

but then when I go to this using a web browser (Firefox 44.0.2) I get "Server not found" and the following on the command line:

```
Fatal Python error: ffi.from_handle() detected that the address passed points to garbage. If it is really the result of ffi.new_handle(), then the Python object has already been garbage collected
Aborted (core dumped)
```

This is on Python 2.7.10 on Fedora 22.

Let me give some more version numbers I see during the installation process:

```
cffi 1.5.2
pycparser 2.14
fibers 1.0.0
pyuv 1.2.0
six 1.10.0
```

**Comment by geertj** [comment]
This bug was caused by not taking a reference to a cdata object. This has been fixed.
